### PR TITLE
Add support for Go 1.5 vendoring

### PR DESCRIPTION
**Pull request by dradtke**
This patch automatically copies any `vendor` folder found into Slurp's workspace so that the new Go vendoring tools can be used.

### CODE REVIEW

**Comment by omeid** [comment]
Thanks for the pull request Damien.

However, I am not sure if this is something that slurp should be handling, I believe it is a more approrpriate task for Godep and alternatives.

Furthermore, I am working on an new iteration of Slurp which completely does away with the code generation part, thought it is not still ready for public just yet. I will ping you when it is up. :)

**Comment by dradtke** [comment]
The reason I implemented this is because without it, Slurp can't get far enough in to the process to start running any tasks because the initial build of the package fails. It copies the package's source to a temporary directory, but Go 1.5 vendoring requires that the dependencies be in the same folder. If Slurp didn't copy the package files anywhere, then it would work just fine without this patch, but this vendoring technique is built directly into the `go` tool, and as such Slurp needs to have some awareness of the technique, or else the two are incompatible.

If your new iteration of Slurp is able to build the package without copying source files, then feel free to ignore this PR, and I'll work off of my forked version until it's ready.

**Comment by omeid** [comment]
@dradtke Thanks for the explaination, I now understand the issue, and yes, the new iteration uses -`pkgdir` and `installsuffix` and does no code generation what so ever. Should be ready in a week or two. :)

**Comment by dradtke** [comment]
Great to hear! I look forward to trying it out.

**Comment by omeid** [comment]
@dradtke Please checkout [Gonzo](https://github.com/omeid/gonzo) and [Kargar](https://github.com/omeid/kargar) and let me know how you go with them!

**Pull request closed without merging**
